### ISSUE TITLE
[suggestion] a conflict in the styles of the variables

### ISSUE THREAD

**Issue by ExplodingDragon** [connorwyatt/sakura-intellij-theme#36]
Variable variables are marked with underscores in the system, while wavy lines indicate that attention is required, which can easily cause confusion.Is there a way to modify it?

THEME:
![图片](https://github.com/connorwyatt/sakura-intellij-theme/assets/33776693/694be886-1de2-4863-b580-d63c25fc3990)

DEFAULT:
![图片](https://github.com/connorwyatt/sakura-intellij-theme/assets/33776693/29f82cd5-8b2d-493b-9c1f-d2f8c2a1da89)

**Comment by connorwyatt** [comment]
@ExplodingDragon Sorry for the delay getting back to you, I'm not sure I understand. Are you saying that you're getting squiggly lines on highlighted variables? If so I don't believe that's part of the theme but would be happy to look into it for you

**Comment by connorwyatt** [comment]
Hi @ExplodingDragon, I looked into this and you're right, there is an issue with the effect on mutable variables. I've fixed it in v0.22.0 which has been uploaded to the marketplace. You should see the fix in the next could of days (although it could be delayed due to the weekend). If you want it early, I will be creating a github release for it that you can install from disk in your IDE

https://github.com/connorwyatt/sakura-intellij-theme/commit/381649aa5555dca3eba038681f0361cef17e93fc
